### PR TITLE
Issue with invisible project when currentproject changes outside of the research window

### PR DESCRIPTION
**Pull request by catgirlfighter**
Currently ResearchPal window has issues if current project was changed outside of the window. Not a big deal in vanilla, but it's a trouble if there are any mods that could do that. This tiny fix should help.

### CODE REVIEW

**Comment by VinaLx** [comment]
Hey catgirlfighter,

Thanks for the contribution!
But the code says:
"When current research queue is empty but actually there is something being researched" instead of the general case in your description of "current research project is changed outside" (where the research queue could be non-empty)

Can you describe the issue in more detail?

By the looks of it I suspect a better fix would be "when the first tech in the queue (including an empty queue) is not what's currently being researched ...", but I'm not sure it fits your case in general.

And thanks for the catch of  `static`.

**Comment by catgirlfighter** [comment]
Yes, what you describe could do the thing too.
Basically, there is a simple mod that makes checks when pawns look for research job, and if currently there is nothing being researched, but could be, it sets a new project. So due to that currentProj is set outside of the window. Vanilla has no issue dealing with that since it uses currentProj directly, but in case of ResearchPal it uses it's own queue and doesn't check any changes in currentProj outside of it's own.

**Comment by VinaLx** [comment]
Okay great what's the name of the mod? So that I can mention it in the change log.

**Comment by catgirlfighter** [comment]
ResearchWhatever, it's not on steam (yet, I think).

**Comment by VinaLx** [comment]
Got it, thanks :)

**Pull request merged**
